---
## https://external-secrets.io/latest/api/clustersecretstore/
##
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-clustersecretstore
spec:
  # provider field contains the configuration to access the provider
  # which contains the secret exactly one provider must be configured.
  provider:
    vault:
      # server: https://vault.devenv.local:8443
      server: http://devops-vault.devops-system.svc.cluster.local:8200
      # Path is the mount path of the Vault KV backend endpoint
      # Used as a path prefix for the external secret key
      path: k8s-secrets
      # Version is the Vault KV secret engine version.
      # This can be either "v1" or "v2", defaults to "v2"
      version: v2
      auth:
        # Kubernetes auth: https://www.vaultproject.io/docs/auth/kubernetes
        kubernetes:
          mountPath: kubernetes
          role: kubernetes-auth-role
          # Optional service account reference
          serviceAccountRef:
            name: devops-vault
            namespace: devops-system

        # # static token: https://www.vaultproject.io/docs/auth/token
        # tokenSecretRef:
        #   name: vault-token-secret
        #   namespace: devops-system
        #   key: token
