---
# docs:
#   - https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/
#   - https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/
#   - https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-argo-workflows
  namespace: devops-system
  annotations:
    argocd.argoproj.io/sync-wave: "420"
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  project: devops-project
  destination:
    name: in-cluster
    namespace: devops-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
    - chart: argo-workflows
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 1.0.14
      helm:
        valueFiles:
          - $valueFiles/app-of-apps/apps/400_cicd/argo-workflows/values.yaml
    - ref: valueFiles
      repoURL: https://github.com/Hiroshi-N-S/local-devops.git
      targetRevision: main

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-argo-workflows-externalsecrets
  namespace: devops-system
  annotations:
    argocd.argoproj.io/sync-wave: "420"
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  project: devops-project
  destination:
    name: in-cluster
    namespace: devops-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
    - path: app-of-apps/apps/400_cicd/argo-workflows/manifests
      repoURL: https://github.com/Hiroshi-N-S/local-devops.git
      targetRevision: main
