---
# docs:
#   - https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/
#   - https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/
#   - https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-kube-prometheus-stack
  namespace: devops-system
  annotations:
    argocd.argoproj.io/sync-wave: "200"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: devops-project
  destination:
    name: in-cluster
    namespace: devops-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 84.2.1
      helm:
        valueFiles:
          - $valueFiles/app-of-apps/apps/200_observability/prometheus/values.yaml
    - ref: valueFiles
      repoURL: https://github.com/Hiroshi-N-S/local-devops.git
      targetRevision: refactor/app-of-apps/domain-based
