---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-default-securitycontext
  annotations:
    policies.kyverno.io/title: Add Default securityContext
    policies.kyverno.io/category: Infrastructure
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: This policy adds a default securityContext to all statefulsets that do not have one defined.
spec:
  rules:
    - name: add-default-securitycontext
      match:
        resources:
          kinds:
            - StatefulSet
            - Deployment
            - DaemonSet
            - Job
            - CronJob
          namespaces:
            - devops-system
      mutate:
        patchStrategicMerge:
          spec:
            template:
              spec:
                securityContext:
                  +(runAsUser): 1000
                  +(runAsGroup): 1000
                  +(runAsNonRoot): true
                  +(fsGroupChangePolicy): "OnRootMismatch"
