---
# docs:
#   - https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/
#   - https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/
#   - https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-minio
  namespace: devops-system
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - argocd.argoproj.io/resources-finalizer/background
spec:
  project: devops-project
  destination:
    name: in-cluster
    namespace: devops-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
    - path: app-of-apps/apps/300_storage/minio/manifests
      repoURL: https://github.com/Hiroshi-N-S/local-devops.git
      targetRevision: refactor/app-of-apps/domain-based
